# Mac-optimized docker-compose for GPU acceleration
version: '3.8'

services:
  # PostgreSQL Database (can run in container)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: kingcro_agentic
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./agentic_copywriter/db/schema.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Ollama for both transcription and text generation (Mac GPU optimized)
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*
      # Mac-specific GPU settings
      - OLLAMA_GPU_LAYERS=35
      - OLLAMA_NUM_PARALLEL=4
    volumes:
      - ollama_data:/root/.ollama
      - ./scripts/init-ollama.sh:/init-ollama.sh
    command: sh -c "/init-ollama.sh && ollama serve"
    deploy:
      resources:
        limits:
          memory: 12G
        reservations:
          memory: 4G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 30s
      timeout: 15s
      retries: 5

  # Whisper for speech-to-text (Mac optimized)
  whisper-server:
    image: onerahmet/openai-whisper-asr-webservice:latest
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  ollama_data:

networks:
  default:
    driver: bridge
